Add Linter
ReemMohamedAbdelfatah/Portfolio-Reem pull request #1
Opened 2022-08-18 02:45 UTC by ReemMohamedAbdelfatah

2022-08-18 19:25 UTC, bobb-Rob requested changes
### Hi @ReemMohamedAbdelfatah , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 19:25 UTC, bobb-Rob commented on index.html
> +        </div>
- [x] Kindly replace the `<div class="wrapper">`  with an `<header>` tag as this tag is used as a page header, it contains the site's title or logo (or both), and the main site navigation. For more info [click here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header).

2022-08-18 19:25 UTC, bobb-Rob commented on index.html
> +            <div class="nav-container">
- [x] Kindly replace the `<div class="nav-container">` with a `<nav>` tag because it is semantically correct to use it to improve your site accessibility. [Click here for more on semantic HTML](https://www.simplilearn.com/tutorials/html-tutorial/html-semantics#:~:text=HTML%20Semantic%20Elements,-Tags&text=The%20element%20defines%20a,the%20section%20of%20the%20document.)

2022-08-18 19:25 UTC, bobb-Rob commented on index.html
> +                <header>
- [x] Please refer to my previous comment on this `<header>` tag and its use. You may need to remove it from here.

2022-08-18 19:25 UTC, bobb-Rob commented on index.html
> +        <div class="header-container">
- [x] Please consider replacing this `<div class="header-container">` with a `<section>` tag because it represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2022-08-18 19:25 UTC, bobb-Rob commented on index.html
> +                  <div id="hello">I'm Reem. glad to see you!</div>
- [x] Kindly replace this `<div id="hello">I'm Reem. glad to see you!</div>` with an `<h1>` tag because it improves your SEO and site accessibility. When a search is done on google (and other search engines), the text you see first is what you put in an `<h1>` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2022-08-18 19:25 UTC, bobb-Rob commented on index.html
> +                     If you like what you see and have a project you need coded, don't hesitate to contact me.  </div>
- [x] Kindly replace this `<div class="about">` with a `<p>` because it is semantically correct and the screen readers and other technologies will thank you.

2022-08-18 19:25 UTC, bobb-Rob commented on index.html
> +                  </div>
- [x] This list of icons should use a `<ul>` tag to group them, and `<li>` per icon; each icon has a link (`<a>` tag). Kindly replace this social media block where you currently are using `<div>` tags with the `<ul>` > `<li>`  > `<a>` as shown below. This is essentially for accessibility and semantic reasons. The `<img>` tags should be nested within the `<a>` tag. 😄 

```
<ul>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
    <li><a href=""></a></li>
</ul>
```

2022-08-18 19:25 UTC, bobb-Rob commented on style.css
> +}
- [x] According to the project requirements, this section should use flexbox to align its content. Kindly fix this.

2022-08-18 19:25 UTC, bobb-Rob commented on README.md
> +This project is MIT licensed.
- [x] Please always remember to edit your README to reflect your current project. Kindly update your README appropriately. 
- [x] Your pull request did not have any description, please ensure you add description before you re-submit for second review. This is best practice and it contains brief outline of thing you implemented. 
- [x] The title of this pull request is also not according to best practice. It should be meaningfully and reflect the current changes made. Kindly update the title to **_Portfolio: setup and mobile first_**

2022-08-19 08:11 UTC, Abenezer-Tilahun requested changes
Hi @ReemMohamedAbdelfatah   

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [x] README file should be descriptive and  all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be present in your Repo. 
- [ ] Pull Request should have a descriptive title telling you what changes are inside and should have a summary describing introduced changes in more detail.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 08:11 UTC, Abenezer-Tilahun commented on index.html
>              </div>
- [ ] Good Job for Implementing changes requested by the previous reviewer. But I recommend you to use `a` tag for logo and `nav` tag for hamburger menu.

2022-08-19 08:11 UTC, Abenezer-Tilahun commented on index.html
> +                        <li class="list-item"><img src="icons/hand-icon.svg" alt="Hand"></li>
- [ ] Good Job for Implementing changes requested by the previous reviewer using `ul` tag to group them, and `li` per icon. Kindly,  try to use  `a` tag  for each icon has a link  to let you connect your social networks with the icons, using `href.`
- [ ] For Social icons please try to follow the Figma design Requirement .You must stick to the design as much as possible (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)
For Social icons your project look likes this :
![C2](https://user-images.githubusercontent.com/93598189/185571836-f45352e0-e972-4970-96bd-6efc0b221b19.PNG)

The Figma design look like : 

![Socail](https://user-images.githubusercontent.com/93598189/185571994-d2793303-bca3-49e7-ad30-06460418fe05.PNG)

2022-08-19 08:18 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] Good job for styling both toolbar and headline section according to Figma design.. Kindly try to  stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)
- [ ] Both toolbar and headline section must have the margins (top, bottom, left, right) defined in the Template design.
Your Project Look likes this : 
![12](https://user-images.githubusercontent.com/93598189/185573634-525bdcbe-5b30-46c7-8362-93eac807a304.PNG)
![123](https://user-images.githubusercontent.com/93598189/185573636-b8751999-1c20-41a2-a453-79d77586ed85.PNG)


The Figma design Look likes this : 
![Figma design](https://user-images.githubusercontent.com/93598189/185573697-e821ee11-553a-4afb-8264-fe311a941f70.PNG)

2022-08-19 08:19 UTC, Abenezer-Tilahun reviewed
- [ ] Good Job try to follow the Figma design requirement , kindly try to stick to design in Template.

2022-08-19 09:48 UTC, sumairq approved these changes
### Hi @ReemMohamedAbdelfatah  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 10:17 UTC, merged